services:
  app:
    image: ghcr.io/misaka-12450/ask-dcnc:latest

    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_IDENTITY_POOL_ID: ${AWS_IDENTITY_POOL_ID}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      AWS_APP_CLIENT_ID: ${AWS_APP_CLIENT_ID}
      COGNITO_USERNAME: ${COGNITO_USERNAME}
      COGNITO_PASSWORD: ${COGNITO_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - app:/app
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    environment:
      CLOUDFLARED_TOKEN: ${CLOUDFLARED_TOKEN}
    restart: always

volumes:
  app:
